// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: costUpdated.proto

package com.zhicheng.wukongcharge.models;

public final class CostUpdatedProto {
  private CostUpdatedProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface costUpdatedReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:costUpdatedReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *更新充电金钱
     * </pre>
     *
     * <code>optional uint32 totalCost = 1;</code>
     */
    boolean hasTotalCost();
    /**
     * <pre>
     *更新充电金钱
     * </pre>
     *
     * <code>optional uint32 totalCost = 1;</code>
     */
    int getTotalCost();

    /**
     * <pre>
     *更新充电时间
     * </pre>
     *
     * <code>optional uint32 totalTime = 2;</code>
     */
    boolean hasTotalTime();
    /**
     * <pre>
     *更新充电时间
     * </pre>
     *
     * <code>optional uint32 totalTime = 2;</code>
     */
    int getTotalTime();

    /**
     * <pre>
     *更新充电总电�?
     * </pre>
     *
     * <code>optional uint32 totalEnergy = 3;</code>
     */
    boolean hasTotalEnergy();
    /**
     * <pre>
     *更新充电总电�?
     * </pre>
     *
     * <code>optional uint32 totalEnergy = 3;</code>
     */
    int getTotalEnergy();

    /**
     * <pre>
     *订单�?
     * </pre>
     *
     * <code>required string transactionId = 4;</code>
     */
    boolean hasTransactionId();
    /**
     * <pre>
     *订单�?
     * </pre>
     *
     * <code>required string transactionId = 4;</code>
     */
    java.lang.String getTransactionId();
    /**
     * <pre>
     *订单�?
     * </pre>
     *
     * <code>required string transactionId = 4;</code>
     */
    com.google.protobuf.ByteString
        getTransactionIdBytes();
  }
  /**
   * Protobuf type {@code costUpdatedReq}
   */
  public  static final class costUpdatedReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:costUpdatedReq)
      costUpdatedReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use costUpdatedReq.newBuilder() to construct.
    private costUpdatedReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private costUpdatedReq() {
      totalCost_ = 0;
      totalTime_ = 0;
      totalEnergy_ = 0;
      transactionId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private costUpdatedReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              totalCost_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              totalTime_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              totalEnergy_ = input.readUInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              transactionId_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq.class, com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq.Builder.class);
    }

    private int bitField0_;
    public static final int TOTALCOST_FIELD_NUMBER = 1;
    private int totalCost_;
    /**
     * <pre>
     *更新充电金钱
     * </pre>
     *
     * <code>optional uint32 totalCost = 1;</code>
     */
    public boolean hasTotalCost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *更新充电金钱
     * </pre>
     *
     * <code>optional uint32 totalCost = 1;</code>
     */
    public int getTotalCost() {
      return totalCost_;
    }

    public static final int TOTALTIME_FIELD_NUMBER = 2;
    private int totalTime_;
    /**
     * <pre>
     *更新充电时间
     * </pre>
     *
     * <code>optional uint32 totalTime = 2;</code>
     */
    public boolean hasTotalTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *更新充电时间
     * </pre>
     *
     * <code>optional uint32 totalTime = 2;</code>
     */
    public int getTotalTime() {
      return totalTime_;
    }

    public static final int TOTALENERGY_FIELD_NUMBER = 3;
    private int totalEnergy_;
    /**
     * <pre>
     *更新充电总电�?
     * </pre>
     *
     * <code>optional uint32 totalEnergy = 3;</code>
     */
    public boolean hasTotalEnergy() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *更新充电总电�?
     * </pre>
     *
     * <code>optional uint32 totalEnergy = 3;</code>
     */
    public int getTotalEnergy() {
      return totalEnergy_;
    }

    public static final int TRANSACTIONID_FIELD_NUMBER = 4;
    private volatile java.lang.Object transactionId_;
    /**
     * <pre>
     *订单�?
     * </pre>
     *
     * <code>required string transactionId = 4;</code>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *订单�?
     * </pre>
     *
     * <code>required string transactionId = 4;</code>
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transactionId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *订单�?
     * </pre>
     *
     * <code>required string transactionId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTransactionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, totalCost_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, totalTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, totalEnergy_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, transactionId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, totalCost_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, totalTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, totalEnergy_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, transactionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq other = (com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq) obj;

      boolean result = true;
      result = result && (hasTotalCost() == other.hasTotalCost());
      if (hasTotalCost()) {
        result = result && (getTotalCost()
            == other.getTotalCost());
      }
      result = result && (hasTotalTime() == other.hasTotalTime());
      if (hasTotalTime()) {
        result = result && (getTotalTime()
            == other.getTotalTime());
      }
      result = result && (hasTotalEnergy() == other.hasTotalEnergy());
      if (hasTotalEnergy()) {
        result = result && (getTotalEnergy()
            == other.getTotalEnergy());
      }
      result = result && (hasTransactionId() == other.hasTransactionId());
      if (hasTransactionId()) {
        result = result && getTransactionId()
            .equals(other.getTransactionId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTotalCost()) {
        hash = (37 * hash) + TOTALCOST_FIELD_NUMBER;
        hash = (53 * hash) + getTotalCost();
      }
      if (hasTotalTime()) {
        hash = (37 * hash) + TOTALTIME_FIELD_NUMBER;
        hash = (53 * hash) + getTotalTime();
      }
      if (hasTotalEnergy()) {
        hash = (37 * hash) + TOTALENERGY_FIELD_NUMBER;
        hash = (53 * hash) + getTotalEnergy();
      }
      if (hasTransactionId()) {
        hash = (37 * hash) + TRANSACTIONID_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code costUpdatedReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:costUpdatedReq)
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq.class, com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        totalCost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        totalTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        totalEnergy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        transactionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedReq_descriptor;
      }

      public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq.getDefaultInstance();
      }

      public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq build() {
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq buildPartial() {
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq result = new com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.totalCost_ = totalCost_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.totalTime_ = totalTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.totalEnergy_ = totalEnergy_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.transactionId_ = transactionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq) {
          return mergeFrom((com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq other) {
        if (other == com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq.getDefaultInstance()) return this;
        if (other.hasTotalCost()) {
          setTotalCost(other.getTotalCost());
        }
        if (other.hasTotalTime()) {
          setTotalTime(other.getTotalTime());
        }
        if (other.hasTotalEnergy()) {
          setTotalEnergy(other.getTotalEnergy());
        }
        if (other.hasTransactionId()) {
          bitField0_ |= 0x00000008;
          transactionId_ = other.transactionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTransactionId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int totalCost_ ;
      /**
       * <pre>
       *更新充电金钱
       * </pre>
       *
       * <code>optional uint32 totalCost = 1;</code>
       */
      public boolean hasTotalCost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *更新充电金钱
       * </pre>
       *
       * <code>optional uint32 totalCost = 1;</code>
       */
      public int getTotalCost() {
        return totalCost_;
      }
      /**
       * <pre>
       *更新充电金钱
       * </pre>
       *
       * <code>optional uint32 totalCost = 1;</code>
       */
      public Builder setTotalCost(int value) {
        bitField0_ |= 0x00000001;
        totalCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新充电金钱
       * </pre>
       *
       * <code>optional uint32 totalCost = 1;</code>
       */
      public Builder clearTotalCost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        totalCost_ = 0;
        onChanged();
        return this;
      }

      private int totalTime_ ;
      /**
       * <pre>
       *更新充电时间
       * </pre>
       *
       * <code>optional uint32 totalTime = 2;</code>
       */
      public boolean hasTotalTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *更新充电时间
       * </pre>
       *
       * <code>optional uint32 totalTime = 2;</code>
       */
      public int getTotalTime() {
        return totalTime_;
      }
      /**
       * <pre>
       *更新充电时间
       * </pre>
       *
       * <code>optional uint32 totalTime = 2;</code>
       */
      public Builder setTotalTime(int value) {
        bitField0_ |= 0x00000002;
        totalTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新充电时间
       * </pre>
       *
       * <code>optional uint32 totalTime = 2;</code>
       */
      public Builder clearTotalTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalTime_ = 0;
        onChanged();
        return this;
      }

      private int totalEnergy_ ;
      /**
       * <pre>
       *更新充电总电�?
       * </pre>
       *
       * <code>optional uint32 totalEnergy = 3;</code>
       */
      public boolean hasTotalEnergy() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *更新充电总电�?
       * </pre>
       *
       * <code>optional uint32 totalEnergy = 3;</code>
       */
      public int getTotalEnergy() {
        return totalEnergy_;
      }
      /**
       * <pre>
       *更新充电总电�?
       * </pre>
       *
       * <code>optional uint32 totalEnergy = 3;</code>
       */
      public Builder setTotalEnergy(int value) {
        bitField0_ |= 0x00000004;
        totalEnergy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新充电总电�?
       * </pre>
       *
       * <code>optional uint32 totalEnergy = 3;</code>
       */
      public Builder clearTotalEnergy() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalEnergy_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object transactionId_ = "";
      /**
       * <pre>
       *订单�?
       * </pre>
       *
       * <code>required string transactionId = 4;</code>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *订单�?
       * </pre>
       *
       * <code>required string transactionId = 4;</code>
       */
      public java.lang.String getTransactionId() {
        java.lang.Object ref = transactionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transactionId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *订单�?
       * </pre>
       *
       * <code>required string transactionId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTransactionIdBytes() {
        java.lang.Object ref = transactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *订单�?
       * </pre>
       *
       * <code>required string transactionId = 4;</code>
       */
      public Builder setTransactionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单�?
       * </pre>
       *
       * <code>required string transactionId = 4;</code>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        transactionId_ = getDefaultInstance().getTransactionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单�?
       * </pre>
       *
       * <code>required string transactionId = 4;</code>
       */
      public Builder setTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        transactionId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:costUpdatedReq)
    }

    // @@protoc_insertion_point(class_scope:costUpdatedReq)
    private static final com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq();
    }

    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<costUpdatedReq>
        PARSER = new com.google.protobuf.AbstractParser<costUpdatedReq>() {
      public costUpdatedReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new costUpdatedReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<costUpdatedReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<costUpdatedReq> getParserForType() {
      return PARSER;
    }

    public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface costUpdatedRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:costUpdatedResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
     */
    com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType getStatus();
  }
  /**
   * Protobuf type {@code costUpdatedResp}
   */
  public  static final class costUpdatedResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:costUpdatedResp)
      costUpdatedRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use costUpdatedResp.newBuilder() to construct.
    private costUpdatedResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private costUpdatedResp() {
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private costUpdatedResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType value = com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.class, com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.Builder.class);
    }

    /**
     * Protobuf enum {@code costUpdatedResp.costUpdatedStatusEnumType}
     */
    public enum costUpdatedStatusEnumType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Accepted = 0;</code>
       */
      Accepted(0),
      /**
       * <code>Rejected = 1;</code>
       */
      Rejected(1),
      ;

      /**
       * <code>Accepted = 0;</code>
       */
      public static final int Accepted_VALUE = 0;
      /**
       * <code>Rejected = 1;</code>
       */
      public static final int Rejected_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static costUpdatedStatusEnumType valueOf(int value) {
        return forNumber(value);
      }

      public static costUpdatedStatusEnumType forNumber(int value) {
        switch (value) {
          case 0: return Accepted;
          case 1: return Rejected;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<costUpdatedStatusEnumType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          costUpdatedStatusEnumType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<costUpdatedStatusEnumType>() {
              public costUpdatedStatusEnumType findValueByNumber(int number) {
                return costUpdatedStatusEnumType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.getDescriptor().getEnumTypes().get(0);
      }

      private static final costUpdatedStatusEnumType[] VALUES = values();

      public static costUpdatedStatusEnumType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private costUpdatedStatusEnumType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:costUpdatedResp.costUpdatedStatusEnumType)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
     */
    public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType getStatus() {
      @SuppressWarnings("deprecation")
      com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType result = com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType.valueOf(status_);
      return result == null ? com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType.Accepted : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp other = (com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && status_ == other.status_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code costUpdatedResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:costUpdatedResp)
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.class, com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.internal_static_costUpdatedResp_descriptor;
      }

      public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.getDefaultInstance();
      }

      public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp build() {
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp buildPartial() {
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp result = new com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp) {
          return mergeFrom((com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp other) {
        if (other == com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
       */
      public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType getStatus() {
        @SuppressWarnings("deprecation")
        com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType result = com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType.valueOf(status_);
        return result == null ? com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType.Accepted : result;
      }
      /**
       * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
       */
      public Builder setStatus(com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp.costUpdatedStatusEnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .costUpdatedResp.costUpdatedStatusEnumType status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:costUpdatedResp)
    }

    // @@protoc_insertion_point(class_scope:costUpdatedResp)
    private static final com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp();
    }

    public static com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<costUpdatedResp>
        PARSER = new com.google.protobuf.AbstractParser<costUpdatedResp>() {
      public costUpdatedResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new costUpdatedResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<costUpdatedResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<costUpdatedResp> getParserForType() {
      return PARSER;
    }

    public com.zhicheng.wukongcharge.models.CostUpdatedProto.costUpdatedResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_costUpdatedReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_costUpdatedReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_costUpdatedResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_costUpdatedResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021costUpdated.proto\"b\n\016costUpdatedReq\022\021\n" +
      "\ttotalCost\030\001 \001(\r\022\021\n\ttotalTime\030\002 \001(\r\022\023\n\013t" +
      "otalEnergy\030\003 \001(\r\022\025\n\rtransactionId\030\004 \002(\t\"" +
      "\206\001\n\017costUpdatedResp\022:\n\006status\030\001 \002(\0162*.co" +
      "stUpdatedResp.costUpdatedStatusEnumType\"" +
      "7\n\031costUpdatedStatusEnumType\022\014\n\010Accepted" +
      "\020\000\022\014\n\010Rejected\020\001B4\n com.charge.protocol." +
      "tomda.modelsB\020CostUpdatedProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_costUpdatedReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_costUpdatedReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_costUpdatedReq_descriptor,
        new java.lang.String[] { "TotalCost", "TotalTime", "TotalEnergy", "TransactionId", });
    internal_static_costUpdatedResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_costUpdatedResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_costUpdatedResp_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
