// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getVariableDataType.proto

package com.zhicheng.wukongcharge.models;

public final class GetVariableDataTypeProto {
  private GetVariableDataTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface getVariableDataTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getVariableDataType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *属�?��?�类型，当前值，�?小�?�，�?大�??
     * </pre>
     *
     * <code>required .attributeEnumType attributeType = 1;</code>
     */
    boolean hasAttributeType();
    /**
     * <pre>
     *属�?��?�类型，当前值，�?小�?�，�?大�??
     * </pre>
     *
     * <code>required .attributeEnumType attributeType = 1;</code>
     */
    com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType getAttributeType();

    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>required .componentType component = 2;</code>
     */
    boolean hasComponent();
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>required .componentType component = 2;</code>
     */
    com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType getComponent();
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>required .componentType component = 2;</code>
     */
    com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder getComponentOrBuilder();

    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>required .variableType variable = 3;</code>
     */
    boolean hasVariable();
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>required .variableType variable = 3;</code>
     */
    com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getVariable();
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>required .variableType variable = 3;</code>
     */
    com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder getVariableOrBuilder();
  }
  /**
   * Protobuf type {@code getVariableDataType}
   */
  public  static final class getVariableDataType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:getVariableDataType)
      getVariableDataTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getVariableDataType.newBuilder() to construct.
    private getVariableDataType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getVariableDataType() {
      attributeType_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getVariableDataType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType value = com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                attributeType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = component_.toBuilder();
              }
              component_ = input.readMessage(com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(component_);
                component_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = variable_.toBuilder();
              }
              variable_ = input.readMessage(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(variable_);
                variable_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.internal_static_getVariableDataType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.internal_static_getVariableDataType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType.class, com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType.Builder.class);
    }

    private int bitField0_;
    public static final int ATTRIBUTETYPE_FIELD_NUMBER = 1;
    private int attributeType_;
    /**
     * <pre>
     *属�?��?�类型，当前值，�?小�?�，�?大�??
     * </pre>
     *
     * <code>required .attributeEnumType attributeType = 1;</code>
     */
    public boolean hasAttributeType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *属�?��?�类型，当前值，�?小�?�，�?大�??
     * </pre>
     *
     * <code>required .attributeEnumType attributeType = 1;</code>
     */
    public com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType getAttributeType() {
      @SuppressWarnings("deprecation")
      com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType result = com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.valueOf(attributeType_);
      return result == null ? com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.Actual : result;
    }

    public static final int COMPONENT_FIELD_NUMBER = 2;
    private com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType component_;
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>required .componentType component = 2;</code>
     */
    public boolean hasComponent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>required .componentType component = 2;</code>
     */
    public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType getComponent() {
      return component_ == null ? com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
    }
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>required .componentType component = 2;</code>
     */
    public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder getComponentOrBuilder() {
      return component_ == null ? com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
    }

    public static final int VARIABLE_FIELD_NUMBER = 3;
    private com.zhicheng.wukongcharge.models.VariableTypeProto.variableType variable_;
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>required .variableType variable = 3;</code>
     */
    public boolean hasVariable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>required .variableType variable = 3;</code>
     */
    public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getVariable() {
      return variable_ == null ? com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
    }
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>required .variableType variable = 3;</code>
     */
    public com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder getVariableOrBuilder() {
      return variable_ == null ? com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAttributeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasComponent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVariable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getComponent().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getVariable().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, attributeType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getComponent());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getVariable());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, attributeType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getComponent());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getVariable());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType other = (com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType) obj;

      boolean result = true;
      result = result && (hasAttributeType() == other.hasAttributeType());
      if (hasAttributeType()) {
        result = result && attributeType_ == other.attributeType_;
      }
      result = result && (hasComponent() == other.hasComponent());
      if (hasComponent()) {
        result = result && getComponent()
            .equals(other.getComponent());
      }
      result = result && (hasVariable() == other.hasVariable());
      if (hasVariable()) {
        result = result && getVariable()
            .equals(other.getVariable());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAttributeType()) {
        hash = (37 * hash) + ATTRIBUTETYPE_FIELD_NUMBER;
        hash = (53 * hash) + attributeType_;
      }
      if (hasComponent()) {
        hash = (37 * hash) + COMPONENT_FIELD_NUMBER;
        hash = (53 * hash) + getComponent().hashCode();
      }
      if (hasVariable()) {
        hash = (37 * hash) + VARIABLE_FIELD_NUMBER;
        hash = (53 * hash) + getVariable().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

     
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
     
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getVariableDataType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getVariableDataType)
        com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.internal_static_getVariableDataType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.internal_static_getVariableDataType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType.class, com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getComponentFieldBuilder();
          getVariableFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        attributeType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (componentBuilder_ == null) {
          component_ = null;
        } else {
          componentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (variableBuilder_ == null) {
          variable_ = null;
        } else {
          variableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.internal_static_getVariableDataType_descriptor;
      }

       
      public com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType.getDefaultInstance();
      }

       
      public com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType build() {
        com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

       
      public com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType buildPartial() {
        com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType result = new com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.attributeType_ = attributeType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (componentBuilder_ == null) {
          result.component_ = component_;
        } else {
          result.component_ = componentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (variableBuilder_ == null) {
          result.variable_ = variable_;
        } else {
          result.variable_ = variableBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType) {
          return mergeFrom((com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType other) {
        if (other == com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType.getDefaultInstance()) return this;
        if (other.hasAttributeType()) {
          setAttributeType(other.getAttributeType());
        }
        if (other.hasComponent()) {
          mergeComponent(other.getComponent());
        }
        if (other.hasVariable()) {
          mergeVariable(other.getVariable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAttributeType()) {
          return false;
        }
        if (!hasComponent()) {
          return false;
        }
        if (!hasVariable()) {
          return false;
        }
        if (!getComponent().isInitialized()) {
          return false;
        }
        if (!getVariable().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int attributeType_ = 1;
      /**
       * <pre>
       *属�?��?�类型，当前值，�?小�?�，�?大�??
       * </pre>
       *
       * <code>required .attributeEnumType attributeType = 1;</code>
       */
      public boolean hasAttributeType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *属�?��?�类型，当前值，�?小�?�，�?大�??
       * </pre>
       *
       * <code>required .attributeEnumType attributeType = 1;</code>
       */
      public com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType getAttributeType() {
        @SuppressWarnings("deprecation")
        com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType result = com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.valueOf(attributeType_);
        return result == null ? com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.Actual : result;
      }
      /**
       * <pre>
       *属�?��?�类型，当前值，�?小�?�，�?大�??
       * </pre>
       *
       * <code>required .attributeEnumType attributeType = 1;</code>
       */
      public Builder setAttributeType(com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        attributeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *属�?��?�类型，当前值，�?小�?�，�?大�??
       * </pre>
       *
       * <code>required .attributeEnumType attributeType = 1;</code>
       */
      public Builder clearAttributeType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attributeType_ = 1;
        onChanged();
        return this;
      }

      private com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType component_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder> componentBuilder_;
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public boolean hasComponent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType getComponent() {
        if (componentBuilder_ == null) {
          return component_ == null ? com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
        } else {
          return componentBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public Builder setComponent(com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType value) {
        if (componentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          component_ = value;
          onChanged();
        } else {
          componentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public Builder setComponent(
          com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder builderForValue) {
        if (componentBuilder_ == null) {
          component_ = builderForValue.build();
          onChanged();
        } else {
          componentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public Builder mergeComponent(com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType value) {
        if (componentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              component_ != null &&
              component_ != com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance()) {
            component_ =
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.newBuilder(component_).mergeFrom(value).buildPartial();
          } else {
            component_ = value;
          }
          onChanged();
        } else {
          componentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public Builder clearComponent() {
        if (componentBuilder_ == null) {
          component_ = null;
          onChanged();
        } else {
          componentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder getComponentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getComponentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder getComponentOrBuilder() {
        if (componentBuilder_ != null) {
          return componentBuilder_.getMessageOrBuilder();
        } else {
          return component_ == null ?
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
        }
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>required .componentType component = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder> 
          getComponentFieldBuilder() {
        if (componentBuilder_ == null) {
          componentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder>(
                  getComponent(),
                  getParentForChildren(),
                  isClean());
          component_ = null;
        }
        return componentBuilder_;
      }

      private com.zhicheng.wukongcharge.models.VariableTypeProto.variableType variable_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.VariableTypeProto.variableType, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder, com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder> variableBuilder_;
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public boolean hasVariable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getVariable() {
        if (variableBuilder_ == null) {
          return variable_ == null ? com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
        } else {
          return variableBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public Builder setVariable(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType value) {
        if (variableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          variable_ = value;
          onChanged();
        } else {
          variableBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public Builder setVariable(
          com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder builderForValue) {
        if (variableBuilder_ == null) {
          variable_ = builderForValue.build();
          onChanged();
        } else {
          variableBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public Builder mergeVariable(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType value) {
        if (variableBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              variable_ != null &&
              variable_ != com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance()) {
            variable_ =
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.newBuilder(variable_).mergeFrom(value).buildPartial();
          } else {
            variable_ = value;
          }
          onChanged();
        } else {
          variableBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public Builder clearVariable() {
        if (variableBuilder_ == null) {
          variable_ = null;
          onChanged();
        } else {
          variableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder getVariableBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getVariableFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder getVariableOrBuilder() {
        if (variableBuilder_ != null) {
          return variableBuilder_.getMessageOrBuilder();
        } else {
          return variable_ == null ?
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
        }
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>required .variableType variable = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.VariableTypeProto.variableType, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder, com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder> 
          getVariableFieldBuilder() {
        if (variableBuilder_ == null) {
          variableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder, com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder>(
                  getVariable(),
                  getParentForChildren(),
                  isClean());
          variable_ = null;
        }
        return variableBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:getVariableDataType)
    }

    // @@protoc_insertion_point(class_scope:getVariableDataType)
    private static final com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType();
    }

    public static com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<getVariableDataType>
        PARSER = new com.google.protobuf.AbstractParser<getVariableDataType>() {
       
      public getVariableDataType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getVariableDataType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getVariableDataType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getVariableDataType> getParserForType() {
      return PARSER;
    }

     
    public com.zhicheng.wukongcharge.models.GetVariableDataTypeProto.getVariableDataType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVariableDataType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVariableDataType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031getVariableDataType.proto\032\027attributeEn" +
      "umType.proto\032\023componentType.proto\032\022varia" +
      "bleType.proto\"\204\001\n\023getVariableDataType\022)\n" +
      "\rattributeType\030\001 \002(\0162\022.attributeEnumType" +
      "\022!\n\tcomponent\030\002 \002(\0132\016.componentType\022\037\n\010v" +
      "ariable\030\003 \002(\0132\r.variableTypeB<\n com.char" +
      "ge.protocol.tomda.modelsB\030GetVariableDat" +
      "aTypeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.getDescriptor(),
          com.zhicheng.wukongcharge.models.ComponentTypeProto.getDescriptor(),
          com.zhicheng.wukongcharge.models.VariableTypeProto.getDescriptor(),
        }, assigner);
    internal_static_getVariableDataType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getVariableDataType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVariableDataType_descriptor,
        new java.lang.String[] { "AttributeType", "Component", "Variable", });
    com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.getDescriptor();
    com.zhicheng.wukongcharge.models.ComponentTypeProto.getDescriptor();
    com.zhicheng.wukongcharge.models.VariableTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
