// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: setVariableResultType.proto

package com.zhicheng.wukongcharge.models;

public final class SetVariableResultTypeProto {
  private SetVariableResultTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface setVariableResultTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:setVariableResultType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *状�??
     * </pre>
     *
     * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
     */
    boolean hasAttributeStatus();
    /**
     * <pre>
     *状�??
     * </pre>
     *
     * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
     */
    com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType getAttributeStatus();

    /**
     * <pre>
     *属�?�类�?
     * </pre>
     *
     * <code>optional .attributeEnumType attributeType = 2;</code>
     */
    boolean hasAttributeType();
    /**
     * <pre>
     *属�?�类�?
     * </pre>
     *
     * <code>optional .attributeEnumType attributeType = 2;</code>
     */
    com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType getAttributeType();

    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>optional .componentType component = 3;</code>
     */
    boolean hasComponent();
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>optional .componentType component = 3;</code>
     */
    com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType getComponent();
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>optional .componentType component = 3;</code>
     */
    com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder getComponentOrBuilder();

    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>optional .variableType variable = 4;</code>
     */
    boolean hasVariable();
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>optional .variableType variable = 4;</code>
     */
    com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getVariable();
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>optional .variableType variable = 4;</code>
     */
    com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder getVariableOrBuilder();
  }
  /**
   * Protobuf type {@code setVariableResultType}
   */
  public  static final class setVariableResultType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:setVariableResultType)
      setVariableResultTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use setVariableResultType.newBuilder() to construct.
    private setVariableResultType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private setVariableResultType() {
      attributeStatus_ = 0;
      attributeType_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private setVariableResultType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType value = com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                attributeStatus_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType value = com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                attributeType_ = rawValue;
              }
              break;
            }
            case 26: {
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = component_.toBuilder();
              }
              component_ = input.readMessage(com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(component_);
                component_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = variable_.toBuilder();
              }
              variable_ = input.readMessage(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(variable_);
                variable_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.internal_static_setVariableResultType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.internal_static_setVariableResultType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.class, com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.Builder.class);
    }

    /**
     * Protobuf enum {@code setVariableResultType.setVariableStatusEnumType}
     */
    public enum setVariableStatusEnumType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *设置成功
       * </pre>
       *
       * <code>Accepted = 0;</code>
       */
      Accepted(0),
      /**
       * <pre>
       *设置失败
       * </pre>
       *
       * <code>Rejected = 1;</code>
       */
      Rejected(1),
      /**
       * <pre>
       *错误的�??
       * </pre>
       *
       * <code>InvalidValue = 2;</code>
       */
      InvalidValue(2),
      /**
       * <pre>
       *未知组件
       * </pre>
       *
       * <code>UnknownComponent = 3;</code>
       */
      UnknownComponent(3),
      /**
       * <pre>
       *未知变量
       * </pre>
       *
       * <code>UnknownVariable = 4;</code>
       */
      UnknownVariable(4),
      /**
       * <pre>
       *未知属�?�类�?
       * </pre>
       *
       * <code>UnknowAttributeType = 5;</code>
       */
      UnknowAttributeType(5),
      /**
       * <pre>
       *超过范围设置
       * </pre>
       *
       * <code>OutOfRange = 6;</code>
       */
      OutOfRange(6),
      /**
       * <pre>
       *设置后会重启
       * </pre>
       *
       * <code>RebootRequired = 7;</code>
       */
      RebootRequired(7),
      ;

      /**
       * <pre>
       *设置成功
       * </pre>
       *
       * <code>Accepted = 0;</code>
       */
      public static final int Accepted_VALUE = 0;
      /**
       * <pre>
       *设置失败
       * </pre>
       *
       * <code>Rejected = 1;</code>
       */
      public static final int Rejected_VALUE = 1;
      /**
       * <pre>
       *错误的�??
       * </pre>
       *
       * <code>InvalidValue = 2;</code>
       */
      public static final int InvalidValue_VALUE = 2;
      /**
       * <pre>
       *未知组件
       * </pre>
       *
       * <code>UnknownComponent = 3;</code>
       */
      public static final int UnknownComponent_VALUE = 3;
      /**
       * <pre>
       *未知变量
       * </pre>
       *
       * <code>UnknownVariable = 4;</code>
       */
      public static final int UnknownVariable_VALUE = 4;
      /**
       * <pre>
       *未知属�?�类�?
       * </pre>
       *
       * <code>UnknowAttributeType = 5;</code>
       */
      public static final int UnknowAttributeType_VALUE = 5;
      /**
       * <pre>
       *超过范围设置
       * </pre>
       *
       * <code>OutOfRange = 6;</code>
       */
      public static final int OutOfRange_VALUE = 6;
      /**
       * <pre>
       *设置后会重启
       * </pre>
       *
       * <code>RebootRequired = 7;</code>
       */
      public static final int RebootRequired_VALUE = 7;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static setVariableStatusEnumType valueOf(int value) {
        return forNumber(value);
      }

      public static setVariableStatusEnumType forNumber(int value) {
        switch (value) {
          case 0: return Accepted;
          case 1: return Rejected;
          case 2: return InvalidValue;
          case 3: return UnknownComponent;
          case 4: return UnknownVariable;
          case 5: return UnknowAttributeType;
          case 6: return OutOfRange;
          case 7: return RebootRequired;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<setVariableStatusEnumType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          setVariableStatusEnumType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<setVariableStatusEnumType>() {
              public setVariableStatusEnumType findValueByNumber(int number) {
                return setVariableStatusEnumType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.getDescriptor().getEnumTypes().get(0);
      }

      private static final setVariableStatusEnumType[] VALUES = values();

      public static setVariableStatusEnumType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private setVariableStatusEnumType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:setVariableResultType.setVariableStatusEnumType)
    }

    private int bitField0_;
    public static final int ATTRIBUTESTATUS_FIELD_NUMBER = 1;
    private int attributeStatus_;
    /**
     * <pre>
     *状�??
     * </pre>
     *
     * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
     */
    public boolean hasAttributeStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *状�??
     * </pre>
     *
     * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
     */
    public com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType getAttributeStatus() {
      @SuppressWarnings("deprecation")
      com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType result = com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType.valueOf(attributeStatus_);
      return result == null ? com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType.Accepted : result;
    }

    public static final int ATTRIBUTETYPE_FIELD_NUMBER = 2;
    private int attributeType_;
    /**
     * <pre>
     *属�?�类�?
     * </pre>
     *
     * <code>optional .attributeEnumType attributeType = 2;</code>
     */
    public boolean hasAttributeType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *属�?�类�?
     * </pre>
     *
     * <code>optional .attributeEnumType attributeType = 2;</code>
     */
    public com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType getAttributeType() {
      @SuppressWarnings("deprecation")
      com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType result = com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.valueOf(attributeType_);
      return result == null ? com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.Actual : result;
    }

    public static final int COMPONENT_FIELD_NUMBER = 3;
    private com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType component_;
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>optional .componentType component = 3;</code>
     */
    public boolean hasComponent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>optional .componentType component = 3;</code>
     */
    public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType getComponent() {
      return component_ == null ? com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
    }
    /**
     * <pre>
     *组件
     * </pre>
     *
     * <code>optional .componentType component = 3;</code>
     */
    public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder getComponentOrBuilder() {
      return component_ == null ? com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
    }

    public static final int VARIABLE_FIELD_NUMBER = 4;
    private com.zhicheng.wukongcharge.models.VariableTypeProto.variableType variable_;
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>optional .variableType variable = 4;</code>
     */
    public boolean hasVariable() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>optional .variableType variable = 4;</code>
     */
    public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getVariable() {
      return variable_ == null ? com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
    }
    /**
     * <pre>
     *变量
     * </pre>
     *
     * <code>optional .variableType variable = 4;</code>
     */
    public com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder getVariableOrBuilder() {
      return variable_ == null ? com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAttributeStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasComponent()) {
        if (!getComponent().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasVariable()) {
        if (!getVariable().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, attributeStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, attributeType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getComponent());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getVariable());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, attributeStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, attributeType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getComponent());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getVariable());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType other = (com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType) obj;

      boolean result = true;
      result = result && (hasAttributeStatus() == other.hasAttributeStatus());
      if (hasAttributeStatus()) {
        result = result && attributeStatus_ == other.attributeStatus_;
      }
      result = result && (hasAttributeType() == other.hasAttributeType());
      if (hasAttributeType()) {
        result = result && attributeType_ == other.attributeType_;
      }
      result = result && (hasComponent() == other.hasComponent());
      if (hasComponent()) {
        result = result && getComponent()
            .equals(other.getComponent());
      }
      result = result && (hasVariable() == other.hasVariable());
      if (hasVariable()) {
        result = result && getVariable()
            .equals(other.getVariable());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAttributeStatus()) {
        hash = (37 * hash) + ATTRIBUTESTATUS_FIELD_NUMBER;
        hash = (53 * hash) + attributeStatus_;
      }
      if (hasAttributeType()) {
        hash = (37 * hash) + ATTRIBUTETYPE_FIELD_NUMBER;
        hash = (53 * hash) + attributeType_;
      }
      if (hasComponent()) {
        hash = (37 * hash) + COMPONENT_FIELD_NUMBER;
        hash = (53 * hash) + getComponent().hashCode();
      }
      if (hasVariable()) {
        hash = (37 * hash) + VARIABLE_FIELD_NUMBER;
        hash = (53 * hash) + getVariable().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
     
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code setVariableResultType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:setVariableResultType)
        com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.internal_static_setVariableResultType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.internal_static_setVariableResultType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.class, com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getComponentFieldBuilder();
          getVariableFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        attributeStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        attributeType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (componentBuilder_ == null) {
          component_ = null;
        } else {
          componentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (variableBuilder_ == null) {
          variable_ = null;
        } else {
          variableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.internal_static_setVariableResultType_descriptor;
      }

       
      public com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.getDefaultInstance();
      }

       
      public com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType build() {
        com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

       
      public com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType buildPartial() {
        com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType result = new com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.attributeStatus_ = attributeStatus_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attributeType_ = attributeType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (componentBuilder_ == null) {
          result.component_ = component_;
        } else {
          result.component_ = componentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (variableBuilder_ == null) {
          result.variable_ = variable_;
        } else {
          result.variable_ = variableBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType) {
          return mergeFrom((com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType other) {
        if (other == com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.getDefaultInstance()) return this;
        if (other.hasAttributeStatus()) {
          setAttributeStatus(other.getAttributeStatus());
        }
        if (other.hasAttributeType()) {
          setAttributeType(other.getAttributeType());
        }
        if (other.hasComponent()) {
          mergeComponent(other.getComponent());
        }
        if (other.hasVariable()) {
          mergeVariable(other.getVariable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAttributeStatus()) {
          return false;
        }
        if (hasComponent()) {
          if (!getComponent().isInitialized()) {
            return false;
          }
        }
        if (hasVariable()) {
          if (!getVariable().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int attributeStatus_ = 0;
      /**
       * <pre>
       *状�??
       * </pre>
       *
       * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
       */
      public boolean hasAttributeStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *状�??
       * </pre>
       *
       * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
       */
      public com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType getAttributeStatus() {
        @SuppressWarnings("deprecation")
        com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType result = com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType.valueOf(attributeStatus_);
        return result == null ? com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType.Accepted : result;
      }
      /**
       * <pre>
       *状�??
       * </pre>
       *
       * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
       */
      public Builder setAttributeStatus(com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType.setVariableStatusEnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        attributeStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *状�??
       * </pre>
       *
       * <code>required .setVariableResultType.setVariableStatusEnumType attributeStatus = 1;</code>
       */
      public Builder clearAttributeStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attributeStatus_ = 0;
        onChanged();
        return this;
      }

      private int attributeType_ = 1;
      /**
       * <pre>
       *属�?�类�?
       * </pre>
       *
       * <code>optional .attributeEnumType attributeType = 2;</code>
       */
      public boolean hasAttributeType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *属�?�类�?
       * </pre>
       *
       * <code>optional .attributeEnumType attributeType = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType getAttributeType() {
        @SuppressWarnings("deprecation")
        com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType result = com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.valueOf(attributeType_);
        return result == null ? com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType.Actual : result;
      }
      /**
       * <pre>
       *属�?�类�?
       * </pre>
       *
       * <code>optional .attributeEnumType attributeType = 2;</code>
       */
      public Builder setAttributeType(com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.attributeEnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        attributeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *属�?�类�?
       * </pre>
       *
       * <code>optional .attributeEnumType attributeType = 2;</code>
       */
      public Builder clearAttributeType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        attributeType_ = 1;
        onChanged();
        return this;
      }

      private com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType component_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder> componentBuilder_;
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public boolean hasComponent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType getComponent() {
        if (componentBuilder_ == null) {
          return component_ == null ? com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
        } else {
          return componentBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public Builder setComponent(com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType value) {
        if (componentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          component_ = value;
          onChanged();
        } else {
          componentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public Builder setComponent(
          com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder builderForValue) {
        if (componentBuilder_ == null) {
          component_ = builderForValue.build();
          onChanged();
        } else {
          componentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public Builder mergeComponent(com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType value) {
        if (componentBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              component_ != null &&
              component_ != com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance()) {
            component_ =
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.newBuilder(component_).mergeFrom(value).buildPartial();
          } else {
            component_ = value;
          }
          onChanged();
        } else {
          componentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public Builder clearComponent() {
        if (componentBuilder_ == null) {
          component_ = null;
          onChanged();
        } else {
          componentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder getComponentBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getComponentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder getComponentOrBuilder() {
        if (componentBuilder_ != null) {
          return componentBuilder_.getMessageOrBuilder();
        } else {
          return component_ == null ?
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.getDefaultInstance() : component_;
        }
      }
      /**
       * <pre>
       *组件
       * </pre>
       *
       * <code>optional .componentType component = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder> 
          getComponentFieldBuilder() {
        if (componentBuilder_ == null) {
          componentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentType.Builder, com.zhicheng.wukongcharge.models.ComponentTypeProto.componentTypeOrBuilder>(
                  getComponent(),
                  getParentForChildren(),
                  isClean());
          component_ = null;
        }
        return componentBuilder_;
      }

      private com.zhicheng.wukongcharge.models.VariableTypeProto.variableType variable_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.VariableTypeProto.variableType, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder, com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder> variableBuilder_;
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public boolean hasVariable() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getVariable() {
        if (variableBuilder_ == null) {
          return variable_ == null ? com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
        } else {
          return variableBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public Builder setVariable(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType value) {
        if (variableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          variable_ = value;
          onChanged();
        } else {
          variableBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public Builder setVariable(
          com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder builderForValue) {
        if (variableBuilder_ == null) {
          variable_ = builderForValue.build();
          onChanged();
        } else {
          variableBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public Builder mergeVariable(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType value) {
        if (variableBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              variable_ != null &&
              variable_ != com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance()) {
            variable_ =
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.newBuilder(variable_).mergeFrom(value).buildPartial();
          } else {
            variable_ = value;
          }
          onChanged();
        } else {
          variableBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public Builder clearVariable() {
        if (variableBuilder_ == null) {
          variable_ = null;
          onChanged();
        } else {
          variableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder getVariableBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getVariableFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder getVariableOrBuilder() {
        if (variableBuilder_ != null) {
          return variableBuilder_.getMessageOrBuilder();
        } else {
          return variable_ == null ?
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance() : variable_;
        }
      }
      /**
       * <pre>
       *变量
       * </pre>
       *
       * <code>optional .variableType variable = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.VariableTypeProto.variableType, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder, com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder> 
          getVariableFieldBuilder() {
        if (variableBuilder_ == null) {
          variableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder, com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder>(
                  getVariable(),
                  getParentForChildren(),
                  isClean());
          variable_ = null;
        }
        return variableBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:setVariableResultType)
    }

    // @@protoc_insertion_point(class_scope:setVariableResultType)
    private static final com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType();
    }

    public static com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<setVariableResultType>
        PARSER = new com.google.protobuf.AbstractParser<setVariableResultType>() {
      public setVariableResultType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new setVariableResultType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<setVariableResultType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<setVariableResultType> getParserForType() {
      return PARSER;
    }
    public com.zhicheng.wukongcharge.models.SetVariableResultTypeProto.setVariableResultType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_setVariableResultType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_setVariableResultType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033setVariableResultType.proto\032\027attribute" +
      "EnumType.proto\032\023componentType.proto\032\022var" +
      "iableType.proto\"\205\003\n\025setVariableResultTyp" +
      "e\022I\n\017attributeStatus\030\001 \002(\01620.setVariable" +
      "ResultType.setVariableStatusEnumType\022)\n\r" +
      "attributeType\030\002 \001(\0162\022.attributeEnumType\022" +
      "!\n\tcomponent\030\003 \001(\0132\016.componentType\022\037\n\010va" +
      "riable\030\004 \001(\0132\r.variableType\"\261\001\n\031setVaria" +
      "bleStatusEnumType\022\014\n\010Accepted\020\000\022\014\n\010Rejec" +
      "ted\020\001\022\020\n\014InvalidValue\020\002\022\024\n\020UnknownCompon" +
      "ent\020\003\022\023\n\017UnknownVariable\020\004\022\027\n\023UnknowAttr" +
      "ibuteType\020\005\022\016\n\nOutOfRange\020\006\022\022\n\016RebootReq" +
      "uired\020\007B>\n com.charge.protocol.tomda.mod" +
      "elsB\032SetVariableResultTypeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.getDescriptor(),
          com.zhicheng.wukongcharge.models.ComponentTypeProto.getDescriptor(),
          com.zhicheng.wukongcharge.models.VariableTypeProto.getDescriptor(),
        }, assigner);
    internal_static_setVariableResultType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_setVariableResultType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_setVariableResultType_descriptor,
        new java.lang.String[] { "AttributeStatus", "AttributeType", "Component", "Variable", });
    com.zhicheng.wukongcharge.models.AttributeEnumTypeProto.getDescriptor();
    com.zhicheng.wukongcharge.models.ComponentTypeProto.getDescriptor();
    com.zhicheng.wukongcharge.models.VariableTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
