// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statusNotification.proto

package com.zhicheng.wukongcharge.models;

public final class StatusNotificationProto {
  private StatusNotificationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface statusNotificationReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:statusNotificationReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *上报时间
     * </pre>
     *
     * <code>required string timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     *上报时间
     * </pre>
     *
     * <code>required string timestamp = 1;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     *上报时间
     * </pre>
     *
     * <code>required string timestamp = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    java.util.List<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType> 
        getConnectorsStatusList();
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType getConnectorsStatus(int index);
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    int getConnectorsStatusCount();
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    java.util.List<? extends com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder> 
        getConnectorsStatusOrBuilderList();
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder getConnectorsStatusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code statusNotificationReq}
   */
  public  static final class statusNotificationReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:statusNotificationReq)
      statusNotificationReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use statusNotificationReq.newBuilder() to construct.
    private statusNotificationReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private statusNotificationReq() {
      timestamp_ = "";
      connectorsStatus_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private statusNotificationReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              timestamp_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                connectorsStatus_ = new java.util.ArrayList<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType>();
                mutable_bitField0_ |= 0x00000002;
              }
              connectorsStatus_.add(
                  input.readMessage(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          connectorsStatus_ = java.util.Collections.unmodifiableList(connectorsStatus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.class, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.Builder.class);
    }

    /**
     * Protobuf enum {@code statusNotificationReq.connectorStatusEnumType}
     */
    public enum connectorStatusEnumType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *插头可用
       * </pre>
       *
       * <code>Available = 0;</code>
       */
      Available(0),
      /**
       * <pre>
       *插头被占�?
       * </pre>
       *
       * <code>Occupied = 1;</code>
       */
      Occupied(1),
      /**
       * <pre>
       *插头被预�?
       * </pre>
       *
       * <code>Reserved = 2;</code>
       */
      Reserved(2),
      /**
       * <pre>
       *插头不可�?(CSO设置插头不可�?)
       * </pre>
       *
       * <code>Unavailable = 3;</code>
       */
      Unavailable(3),
      /**
       * <pre>
       *插头有故�?(如过流，温度过高)
       * </pre>
       *
       * <code>Faulted = 4;</code>
       */
      Faulted(4),
      ;

      /**
       * <pre>
       *插头可用
       * </pre>
       *
       * <code>Available = 0;</code>
       */
      public static final int Available_VALUE = 0;
      /**
       * <pre>
       *插头被占�?
       * </pre>
       *
       * <code>Occupied = 1;</code>
       */
      public static final int Occupied_VALUE = 1;
      /**
       * <pre>
       *插头被预�?
       * </pre>
       *
       * <code>Reserved = 2;</code>
       */
      public static final int Reserved_VALUE = 2;
      /**
       * <pre>
       *插头不可�?(CSO设置插头不可�?)
       * </pre>
       *
       * <code>Unavailable = 3;</code>
       */
      public static final int Unavailable_VALUE = 3;
      /**
       * <pre>
       *插头有故�?(如过流，温度过高)
       * </pre>
       *
       * <code>Faulted = 4;</code>
       */
      public static final int Faulted_VALUE = 4;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static connectorStatusEnumType valueOf(int value) {
        return forNumber(value);
      }

      public static connectorStatusEnumType forNumber(int value) {
        switch (value) {
          case 0: return Available;
          case 1: return Occupied;
          case 2: return Reserved;
          case 3: return Unavailable;
          case 4: return Faulted;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<connectorStatusEnumType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          connectorStatusEnumType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<connectorStatusEnumType>() {
              public connectorStatusEnumType findValueByNumber(int number) {
                return connectorStatusEnumType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final connectorStatusEnumType[] VALUES = values();

      public static connectorStatusEnumType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private connectorStatusEnumType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:statusNotificationReq.connectorStatusEnumType)
    }

    public interface connectorsStatusTypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:statusNotificationReq.connectorsStatusType)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *插头�?
       * </pre>
       *
       * <code>required uint32 connectorId = 1;</code>
       */
      boolean hasConnectorId();
      /**
       * <pre>
       *插头�?
       * </pre>
       *
       * <code>required uint32 connectorId = 1;</code>
       */
      int getConnectorId();

      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
       */
      boolean hasConnectorStatus();
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
       */
      com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType getConnectorStatus();

      /**
       * <pre>
       *如果Faulted，附带的错误�?
       * </pre>
       *
       * <code>optional int32 faultCode = 3;</code>
       */
      boolean hasFaultCode();
      /**
       * <pre>
       *如果Faulted，附带的错误�?
       * </pre>
       *
       * <code>optional int32 faultCode = 3;</code>
       */
      int getFaultCode();
    }
    /**
     * Protobuf type {@code statusNotificationReq.connectorsStatusType}
     */
    public  static final class connectorsStatusType extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:statusNotificationReq.connectorsStatusType)
        connectorsStatusTypeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use connectorsStatusType.newBuilder() to construct.
      private connectorsStatusType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private connectorsStatusType() {
        connectorId_ = 0;
        connectorStatus_ = 0;
        faultCode_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private connectorsStatusType(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                connectorId_ = input.readUInt32();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType value = com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  connectorStatus_ = rawValue;
                }
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                faultCode_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_connectorsStatusType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_connectorsStatusType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.class, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder.class);
      }

      private int bitField0_;
      public static final int CONNECTORID_FIELD_NUMBER = 1;
      private int connectorId_;
      /**
       * <pre>
       *插头�?
       * </pre>
       *
       * <code>required uint32 connectorId = 1;</code>
       */
      public boolean hasConnectorId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *插头�?
       * </pre>
       *
       * <code>required uint32 connectorId = 1;</code>
       */
      public int getConnectorId() {
        return connectorId_;
      }

      public static final int CONNECTORSTATUS_FIELD_NUMBER = 2;
      private int connectorStatus_;
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
       */
      public boolean hasConnectorStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType getConnectorStatus() {
        @SuppressWarnings("deprecation")
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType result = com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType.valueOf(connectorStatus_);
        return result == null ? com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType.Available : result;
      }

      public static final int FAULTCODE_FIELD_NUMBER = 3;
      private int faultCode_;
      /**
       * <pre>
       *如果Faulted，附带的错误�?
       * </pre>
       *
       * <code>optional int32 faultCode = 3;</code>
       */
      public boolean hasFaultCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *如果Faulted，附带的错误�?
       * </pre>
       *
       * <code>optional int32 faultCode = 3;</code>
       */
      public int getFaultCode() {
        return faultCode_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasConnectorId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasConnectorStatus()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, connectorId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, connectorStatus_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, faultCode_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, connectorId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, connectorStatus_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, faultCode_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType)) {
          return super.equals(obj);
        }
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType other = (com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType) obj;

        boolean result = true;
        result = result && (hasConnectorId() == other.hasConnectorId());
        if (hasConnectorId()) {
          result = result && (getConnectorId()
              == other.getConnectorId());
        }
        result = result && (hasConnectorStatus() == other.hasConnectorStatus());
        if (hasConnectorStatus()) {
          result = result && connectorStatus_ == other.connectorStatus_;
        }
        result = result && (hasFaultCode() == other.hasFaultCode());
        if (hasFaultCode()) {
          result = result && (getFaultCode()
              == other.getFaultCode());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasConnectorId()) {
          hash = (37 * hash) + CONNECTORID_FIELD_NUMBER;
          hash = (53 * hash) + getConnectorId();
        }
        if (hasConnectorStatus()) {
          hash = (37 * hash) + CONNECTORSTATUS_FIELD_NUMBER;
          hash = (53 * hash) + connectorStatus_;
        }
        if (hasFaultCode()) {
          hash = (37 * hash) + FAULTCODE_FIELD_NUMBER;
          hash = (53 * hash) + getFaultCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

       
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
       
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code statusNotificationReq.connectorsStatusType}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:statusNotificationReq.connectorsStatusType)
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_connectorsStatusType_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_connectorsStatusType_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.class, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder.class);
        }

        // Construct using com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          connectorId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          connectorStatus_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          faultCode_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_connectorsStatusType_descriptor;
        }

         
        public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType getDefaultInstanceForType() {
          return com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.getDefaultInstance();
        }

         
        public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType build() {
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

         
        public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType buildPartial() {
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType result = new com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.connectorId_ = connectorId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.connectorStatus_ = connectorStatus_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.faultCode_ = faultCode_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType) {
            return mergeFrom((com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType other) {
          if (other == com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.getDefaultInstance()) return this;
          if (other.hasConnectorId()) {
            setConnectorId(other.getConnectorId());
          }
          if (other.hasConnectorStatus()) {
            setConnectorStatus(other.getConnectorStatus());
          }
          if (other.hasFaultCode()) {
            setFaultCode(other.getFaultCode());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasConnectorId()) {
            return false;
          }
          if (!hasConnectorStatus()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int connectorId_ ;
        /**
         * <pre>
         *插头�?
         * </pre>
         *
         * <code>required uint32 connectorId = 1;</code>
         */
        public boolean hasConnectorId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <pre>
         *插头�?
         * </pre>
         *
         * <code>required uint32 connectorId = 1;</code>
         */
        public int getConnectorId() {
          return connectorId_;
        }
        /**
         * <pre>
         *插头�?
         * </pre>
         *
         * <code>required uint32 connectorId = 1;</code>
         */
        public Builder setConnectorId(int value) {
          bitField0_ |= 0x00000001;
          connectorId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *插头�?
         * </pre>
         *
         * <code>required uint32 connectorId = 1;</code>
         */
        public Builder clearConnectorId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          connectorId_ = 0;
          onChanged();
          return this;
        }

        private int connectorStatus_ = 0;
        /**
         * <pre>
         *插头状�??
         * </pre>
         *
         * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
         */
        public boolean hasConnectorStatus() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <pre>
         *插头状�??
         * </pre>
         *
         * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
         */
        public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType getConnectorStatus() {
          @SuppressWarnings("deprecation")
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType result = com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType.valueOf(connectorStatus_);
          return result == null ? com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType.Available : result;
        }
        /**
         * <pre>
         *插头状�??
         * </pre>
         *
         * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
         */
        public Builder setConnectorStatus(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorStatusEnumType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          connectorStatus_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *插头状�??
         * </pre>
         *
         * <code>required .statusNotificationReq.connectorStatusEnumType connectorStatus = 2;</code>
         */
        public Builder clearConnectorStatus() {
          bitField0_ = (bitField0_ & ~0x00000002);
          connectorStatus_ = 0;
          onChanged();
          return this;
        }

        private int faultCode_ ;
        /**
         * <pre>
         *如果Faulted，附带的错误�?
         * </pre>
         *
         * <code>optional int32 faultCode = 3;</code>
         */
        public boolean hasFaultCode() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <pre>
         *如果Faulted，附带的错误�?
         * </pre>
         *
         * <code>optional int32 faultCode = 3;</code>
         */
        public int getFaultCode() {
          return faultCode_;
        }
        /**
         * <pre>
         *如果Faulted，附带的错误�?
         * </pre>
         *
         * <code>optional int32 faultCode = 3;</code>
         */
        public Builder setFaultCode(int value) {
          bitField0_ |= 0x00000004;
          faultCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *如果Faulted，附带的错误�?
         * </pre>
         *
         * <code>optional int32 faultCode = 3;</code>
         */
        public Builder clearFaultCode() {
          bitField0_ = (bitField0_ & ~0x00000004);
          faultCode_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:statusNotificationReq.connectorsStatusType)
      }

      // @@protoc_insertion_point(class_scope:statusNotificationReq.connectorsStatusType)
      private static final com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType();
      }

      public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<connectorsStatusType>
          PARSER = new com.google.protobuf.AbstractParser<connectorsStatusType>() {
        public connectorsStatusType parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new connectorsStatusType(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<connectorsStatusType> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<connectorsStatusType> getParserForType() {
        return PARSER;
      }
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     *上报时间
     * </pre>
     *
     * <code>required string timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *上报时间
     * </pre>
     *
     * <code>required string timestamp = 1;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *上报时间
     * </pre>
     *
     * <code>required string timestamp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONNECTORSSTATUS_FIELD_NUMBER = 2;
    private java.util.List<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType> connectorsStatus_;
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    public java.util.List<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType> getConnectorsStatusList() {
      return connectorsStatus_;
    }
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    public java.util.List<? extends com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder> 
        getConnectorsStatusOrBuilderList() {
      return connectorsStatus_;
    }
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    public int getConnectorsStatusCount() {
      return connectorsStatus_.size();
    }
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType getConnectorsStatus(int index) {
      return connectorsStatus_.get(index);
    }
    /**
     * <pre>
     *插头状�??
     * </pre>
     *
     * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
     */
    public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder getConnectorsStatusOrBuilder(
        int index) {
      return connectorsStatus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getConnectorsStatusCount(); i++) {
        if (!getConnectorsStatus(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timestamp_);
      }
      for (int i = 0; i < connectorsStatus_.size(); i++) {
        output.writeMessage(2, connectorsStatus_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timestamp_);
      }
      for (int i = 0; i < connectorsStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, connectorsStatus_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq other = (com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq) obj;

      boolean result = true;
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      result = result && getConnectorsStatusList()
          .equals(other.getConnectorsStatusList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (getConnectorsStatusCount() > 0) {
        hash = (37 * hash) + CONNECTORSSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getConnectorsStatusList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code statusNotificationReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:statusNotificationReq)
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.class, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConnectorsStatusFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (connectorsStatusBuilder_ == null) {
          connectorsStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          connectorsStatusBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationReq_descriptor;
      }
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.getDefaultInstance();
      }
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq build() {
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq buildPartial() {
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq result = new com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (connectorsStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            connectorsStatus_ = java.util.Collections.unmodifiableList(connectorsStatus_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.connectorsStatus_ = connectorsStatus_;
        } else {
          result.connectorsStatus_ = connectorsStatusBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq) {
          return mergeFrom((com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq other) {
        if (other == com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000001;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (connectorsStatusBuilder_ == null) {
          if (!other.connectorsStatus_.isEmpty()) {
            if (connectorsStatus_.isEmpty()) {
              connectorsStatus_ = other.connectorsStatus_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureConnectorsStatusIsMutable();
              connectorsStatus_.addAll(other.connectorsStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.connectorsStatus_.isEmpty()) {
            if (connectorsStatusBuilder_.isEmpty()) {
              connectorsStatusBuilder_.dispose();
              connectorsStatusBuilder_ = null;
              connectorsStatus_ = other.connectorsStatus_;
              bitField0_ = (bitField0_ & ~0x00000002);
              connectorsStatusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConnectorsStatusFieldBuilder() : null;
            } else {
              connectorsStatusBuilder_.addAllMessages(other.connectorsStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          return false;
        }
        for (int i = 0; i < getConnectorsStatusCount(); i++) {
          if (!getConnectorsStatus(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       *上报时间
       * </pre>
       *
       * <code>required string timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *上报时间
       * </pre>
       *
       * <code>required string timestamp = 1;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *上报时间
       * </pre>
       *
       * <code>required string timestamp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *上报时间
       * </pre>
       *
       * <code>required string timestamp = 1;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *上报时间
       * </pre>
       *
       * <code>required string timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *上报时间
       * </pre>
       *
       * <code>required string timestamp = 1;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType> connectorsStatus_ =
        java.util.Collections.emptyList();
      private void ensureConnectorsStatusIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          connectorsStatus_ = new java.util.ArrayList<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType>(connectorsStatus_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder> connectorsStatusBuilder_;

      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public java.util.List<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType> getConnectorsStatusList() {
        if (connectorsStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(connectorsStatus_);
        } else {
          return connectorsStatusBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public int getConnectorsStatusCount() {
        if (connectorsStatusBuilder_ == null) {
          return connectorsStatus_.size();
        } else {
          return connectorsStatusBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType getConnectorsStatus(int index) {
        if (connectorsStatusBuilder_ == null) {
          return connectorsStatus_.get(index);
        } else {
          return connectorsStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder setConnectorsStatus(
          int index, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType value) {
        if (connectorsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectorsStatusIsMutable();
          connectorsStatus_.set(index, value);
          onChanged();
        } else {
          connectorsStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder setConnectorsStatus(
          int index, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder builderForValue) {
        if (connectorsStatusBuilder_ == null) {
          ensureConnectorsStatusIsMutable();
          connectorsStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          connectorsStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder addConnectorsStatus(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType value) {
        if (connectorsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectorsStatusIsMutable();
          connectorsStatus_.add(value);
          onChanged();
        } else {
          connectorsStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder addConnectorsStatus(
          int index, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType value) {
        if (connectorsStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectorsStatusIsMutable();
          connectorsStatus_.add(index, value);
          onChanged();
        } else {
          connectorsStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder addConnectorsStatus(
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder builderForValue) {
        if (connectorsStatusBuilder_ == null) {
          ensureConnectorsStatusIsMutable();
          connectorsStatus_.add(builderForValue.build());
          onChanged();
        } else {
          connectorsStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder addConnectorsStatus(
          int index, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder builderForValue) {
        if (connectorsStatusBuilder_ == null) {
          ensureConnectorsStatusIsMutable();
          connectorsStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          connectorsStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder addAllConnectorsStatus(
          java.lang.Iterable<? extends com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType> values) {
        if (connectorsStatusBuilder_ == null) {
          ensureConnectorsStatusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, connectorsStatus_);
          onChanged();
        } else {
          connectorsStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder clearConnectorsStatus() {
        if (connectorsStatusBuilder_ == null) {
          connectorsStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          connectorsStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public Builder removeConnectorsStatus(int index) {
        if (connectorsStatusBuilder_ == null) {
          ensureConnectorsStatusIsMutable();
          connectorsStatus_.remove(index);
          onChanged();
        } else {
          connectorsStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder getConnectorsStatusBuilder(
          int index) {
        return getConnectorsStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder getConnectorsStatusOrBuilder(
          int index) {
        if (connectorsStatusBuilder_ == null) {
          return connectorsStatus_.get(index);  } else {
          return connectorsStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public java.util.List<? extends com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder> 
           getConnectorsStatusOrBuilderList() {
        if (connectorsStatusBuilder_ != null) {
          return connectorsStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(connectorsStatus_);
        }
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder addConnectorsStatusBuilder() {
        return getConnectorsStatusFieldBuilder().addBuilder(
            com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.getDefaultInstance());
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder addConnectorsStatusBuilder(
          int index) {
        return getConnectorsStatusFieldBuilder().addBuilder(
            index, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.getDefaultInstance());
      }
      /**
       * <pre>
       *插头状�??
       * </pre>
       *
       * <code>repeated .statusNotificationReq.connectorsStatusType connectorsStatus = 2;</code>
       */
      public java.util.List<com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder> 
           getConnectorsStatusBuilderList() {
        return getConnectorsStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder> 
          getConnectorsStatusFieldBuilder() {
        if (connectorsStatusBuilder_ == null) {
          connectorsStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusType.Builder, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq.connectorsStatusTypeOrBuilder>(
                  connectorsStatus_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          connectorsStatus_ = null;
        }
        return connectorsStatusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:statusNotificationReq)
    }

    // @@protoc_insertion_point(class_scope:statusNotificationReq)
    private static final com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq();
    }

    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<statusNotificationReq>
        PARSER = new com.google.protobuf.AbstractParser<statusNotificationReq>() {
      public statusNotificationReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new statusNotificationReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<statusNotificationReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<statusNotificationReq> getParserForType() {
      return PARSER;
    }
    public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface statusNotificationRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:statusNotificationResp)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code statusNotificationResp}
   */
  public  static final class statusNotificationResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:statusNotificationResp)
      statusNotificationRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use statusNotificationResp.newBuilder() to construct.
    private statusNotificationResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private statusNotificationResp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private statusNotificationResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp.class, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp other = (com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code statusNotificationResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:statusNotificationResp)
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp.class, com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.internal_static_statusNotificationResp_descriptor;
      }
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp.getDefaultInstance();
      }
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp build() {
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp buildPartial() {
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp result = new com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp) {
          return mergeFrom((com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp other) {
        if (other == com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:statusNotificationResp)
    }

    // @@protoc_insertion_point(class_scope:statusNotificationResp)
    private static final com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp();
    }

    public static com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<statusNotificationResp>
        PARSER = new com.google.protobuf.AbstractParser<statusNotificationResp>() {
      public statusNotificationResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new statusNotificationResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<statusNotificationResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<statusNotificationResp> getParserForType() {
      return PARSER;
    }

    public com.zhicheng.wukongcharge.models.StatusNotificationProto.statusNotificationResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_statusNotificationReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_statusNotificationReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_statusNotificationReq_connectorsStatusType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_statusNotificationReq_connectorsStatusType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_statusNotificationResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_statusNotificationResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030statusNotification.proto\"\337\002\n\025statusNot" +
      "ificationReq\022\021\n\ttimestamp\030\001 \002(\t\022E\n\020conne" +
      "ctorsStatus\030\002 \003(\0132+.statusNotificationRe" +
      "q.connectorsStatusType\032\207\001\n\024connectorsSta" +
      "tusType\022\023\n\013connectorId\030\001 \002(\r\022G\n\017connecto" +
      "rStatus\030\002 \002(\0162..statusNotificationReq.co" +
      "nnectorStatusEnumType\022\021\n\tfaultCode\030\003 \001(\005" +
      "\"b\n\027connectorStatusEnumType\022\r\n\tAvailable" +
      "\020\000\022\014\n\010Occupied\020\001\022\014\n\010Reserved\020\002\022\017\n\013Unavai" +
      "lable\020\003\022\013\n\007Faulted\020\004\"\030\n\026statusNotificati" +
      "onRespB;\n com.charge.protocol.tomda.mode" +
      "lsB\027StatusNotificationProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_statusNotificationReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_statusNotificationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_statusNotificationReq_descriptor,
        new java.lang.String[] { "Timestamp", "ConnectorsStatus", });
    internal_static_statusNotificationReq_connectorsStatusType_descriptor =
      internal_static_statusNotificationReq_descriptor.getNestedTypes().get(0);
    internal_static_statusNotificationReq_connectorsStatusType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_statusNotificationReq_connectorsStatusType_descriptor,
        new java.lang.String[] { "ConnectorId", "ConnectorStatus", "FaultCode", });
    internal_static_statusNotificationResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_statusNotificationResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_statusNotificationResp_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
