// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableCharacteristicsType.proto

package com.zhicheng.wukongcharge.models;

public final class VariableCharacteristicsTypeProto {
  private VariableCharacteristicsTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface variableCharacteristicsTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:variableCharacteristicsType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *属�?��?�单�?
     * </pre>
     *
     * <code>required string units = 1;</code>
     */
    boolean hasUnits();
    /**
     * <pre>
     *属�?��?�单�?
     * </pre>
     *
     * <code>required string units = 1;</code>
     */
    java.lang.String getUnits();
    /**
     * <pre>
     *属�?��?�单�?
     * </pre>
     *
     * <code>required string units = 1;</code>
     */
    com.google.protobuf.ByteString
        getUnitsBytes();

    /**
     * <pre>
     *属�?�数据类�?
     * </pre>
     *
     * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
     */
    boolean hasDataType();
    /**
     * <pre>
     *属�?�数据类�?
     * </pre>
     *
     * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
     */
    com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType getDataType();

    /**
     * <pre>
     *默认固定�?小�??
     * </pre>
     *
     * <code>optional int32 minLimit = 3;</code>
     */
    boolean hasMinLimit();
    /**
     * <pre>
     *默认固定�?小�??
     * </pre>
     *
     * <code>optional int32 minLimit = 3;</code>
     */
    int getMinLimit();

    /**
     * <pre>
     *默认固定�?大�??
     * </pre>
     *
     * <code>optional int32 maxLimit = 4;</code>
     */
    boolean hasMaxLimit();
    /**
     * <pre>
     *默认固定�?大�??
     * </pre>
     *
     * <code>optional int32 maxLimit = 4;</code>
     */
    int getMaxLimit();

    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    java.util.List<java.lang.String>
        getValuesListList();
    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    int getValuesListCount();
    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    java.lang.String getValuesList(int index);
    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    com.google.protobuf.ByteString
        getValuesListBytes(int index);

    /**
     * <pre>
     *该字段是否被监控，当改变时�?�会notifyEvent会上�?
     * </pre>
     *
     * <code>required bool supportsMonitoring = 6;</code>
     */
    boolean hasSupportsMonitoring();
    /**
     * <pre>
     *该字段是否被监控，当改变时�?�会notifyEvent会上�?
     * </pre>
     *
     * <code>required bool supportsMonitoring = 6;</code>
     */
    boolean getSupportsMonitoring();
  }
  /**
   * Protobuf type {@code variableCharacteristicsType}
   */
  public  static final class variableCharacteristicsType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:variableCharacteristicsType)
      variableCharacteristicsTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use variableCharacteristicsType.newBuilder() to construct.
    private variableCharacteristicsType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private variableCharacteristicsType() {
      units_ = "";
      dataType_ = 0;
      minLimit_ = 0;
      maxLimit_ = 0;
      valuesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      supportsMonitoring_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private variableCharacteristicsType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              units_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType value = com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                dataType_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              minLimit_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              maxLimit_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                valuesList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              valuesList_.add(bs);
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              supportsMonitoring_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          valuesList_ = valuesList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.internal_static_variableCharacteristicsType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.internal_static_variableCharacteristicsType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.class, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder.class);
    }

    /**
     * Protobuf enum {@code variableCharacteristicsType.DateEnumType}
     */
    public enum DateEnumType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>String = 0;</code>
       */
      String(0),
      /**
       * <code>Decimal = 1;</code>
       */
      Decimal(1),
      /**
       * <code>Integer = 2;</code>
       */
      Integer(2),
      /**
       * <code>DateTime = 3;</code>
       */
      DateTime(3),
      /**
       * <code>Boolean = 4;</code>
       */
      Boolean(4),
      /**
       * <code>OptionList = 5;</code>
       */
      OptionList(5),
      ;

      /**
       * <code>String = 0;</code>
       */
      public static final int String_VALUE = 0;
      /**
       * <code>Decimal = 1;</code>
       */
      public static final int Decimal_VALUE = 1;
      /**
       * <code>Integer = 2;</code>
       */
      public static final int Integer_VALUE = 2;
      /**
       * <code>DateTime = 3;</code>
       */
      public static final int DateTime_VALUE = 3;
      /**
       * <code>Boolean = 4;</code>
       */
      public static final int Boolean_VALUE = 4;
      /**
       * <code>OptionList = 5;</code>
       */
      public static final int OptionList_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DateEnumType valueOf(int value) {
        return forNumber(value);
      }

      public static DateEnumType forNumber(int value) {
        switch (value) {
          case 0: return String;
          case 1: return Decimal;
          case 2: return Integer;
          case 3: return DateTime;
          case 4: return Boolean;
          case 5: return OptionList;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DateEnumType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DateEnumType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DateEnumType>() {
              public DateEnumType findValueByNumber(int number) {
                return DateEnumType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDescriptor().getEnumTypes().get(0);
      }

      private static final DateEnumType[] VALUES = values();

      public static DateEnumType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DateEnumType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:variableCharacteristicsType.DateEnumType)
    }

    private int bitField0_;
    public static final int UNITS_FIELD_NUMBER = 1;
    private volatile java.lang.Object units_;
    /**
     * <pre>
     *属�?��?�单�?
     * </pre>
     *
     * <code>required string units = 1;</code>
     */
    public boolean hasUnits() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *属�?��?�单�?
     * </pre>
     *
     * <code>required string units = 1;</code>
     */
    public java.lang.String getUnits() {
      java.lang.Object ref = units_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          units_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *属�?��?�单�?
     * </pre>
     *
     * <code>required string units = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUnitsBytes() {
      java.lang.Object ref = units_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        units_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATATYPE_FIELD_NUMBER = 2;
    private int dataType_;
    /**
     * <pre>
     *属�?�数据类�?
     * </pre>
     *
     * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *属�?�数据类�?
     * </pre>
     *
     * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
     */
    public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType getDataType() {
      @SuppressWarnings("deprecation")
      com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType result = com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType.valueOf(dataType_);
      return result == null ? com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType.String : result;
    }

    public static final int MINLIMIT_FIELD_NUMBER = 3;
    private int minLimit_;
    /**
     * <pre>
     *默认固定�?小�??
     * </pre>
     *
     * <code>optional int32 minLimit = 3;</code>
     */
    public boolean hasMinLimit() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *默认固定�?小�??
     * </pre>
     *
     * <code>optional int32 minLimit = 3;</code>
     */
    public int getMinLimit() {
      return minLimit_;
    }

    public static final int MAXLIMIT_FIELD_NUMBER = 4;
    private int maxLimit_;
    /**
     * <pre>
     *默认固定�?大�??
     * </pre>
     *
     * <code>optional int32 maxLimit = 4;</code>
     */
    public boolean hasMaxLimit() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *默认固定�?大�??
     * </pre>
     *
     * <code>optional int32 maxLimit = 4;</code>
     */
    public int getMaxLimit() {
      return maxLimit_;
    }

    public static final int VALUESLIST_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList valuesList_;
    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValuesListList() {
      return valuesList_;
    }
    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    public int getValuesListCount() {
      return valuesList_.size();
    }
    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    public java.lang.String getValuesList(int index) {
      return valuesList_.get(index);
    }
    /**
     * <pre>
     *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
     * </pre>
     *
     * <code>repeated string valuesList = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValuesListBytes(int index) {
      return valuesList_.getByteString(index);
    }

    public static final int SUPPORTSMONITORING_FIELD_NUMBER = 6;
    private boolean supportsMonitoring_;
    /**
     * <pre>
     *该字段是否被监控，当改变时�?�会notifyEvent会上�?
     * </pre>
     *
     * <code>required bool supportsMonitoring = 6;</code>
     */
    public boolean hasSupportsMonitoring() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *该字段是否被监控，当改变时�?�会notifyEvent会上�?
     * </pre>
     *
     * <code>required bool supportsMonitoring = 6;</code>
     */
    public boolean getSupportsMonitoring() {
      return supportsMonitoring_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSupportsMonitoring()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, units_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, dataType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, minLimit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, maxLimit_);
      }
      for (int i = 0; i < valuesList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, valuesList_.getRaw(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, supportsMonitoring_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, units_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, dataType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, minLimit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, maxLimit_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < valuesList_.size(); i++) {
          dataSize += computeStringSizeNoTag(valuesList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValuesListList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, supportsMonitoring_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType other = (com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType) obj;

      boolean result = true;
      result = result && (hasUnits() == other.hasUnits());
      if (hasUnits()) {
        result = result && getUnits()
            .equals(other.getUnits());
      }
      result = result && (hasDataType() == other.hasDataType());
      if (hasDataType()) {
        result = result && dataType_ == other.dataType_;
      }
      result = result && (hasMinLimit() == other.hasMinLimit());
      if (hasMinLimit()) {
        result = result && (getMinLimit()
            == other.getMinLimit());
      }
      result = result && (hasMaxLimit() == other.hasMaxLimit());
      if (hasMaxLimit()) {
        result = result && (getMaxLimit()
            == other.getMaxLimit());
      }
      result = result && getValuesListList()
          .equals(other.getValuesListList());
      result = result && (hasSupportsMonitoring() == other.hasSupportsMonitoring());
      if (hasSupportsMonitoring()) {
        result = result && (getSupportsMonitoring()
            == other.getSupportsMonitoring());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnits()) {
        hash = (37 * hash) + UNITS_FIELD_NUMBER;
        hash = (53 * hash) + getUnits().hashCode();
      }
      if (hasDataType()) {
        hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      if (hasMinLimit()) {
        hash = (37 * hash) + MINLIMIT_FIELD_NUMBER;
        hash = (53 * hash) + getMinLimit();
      }
      if (hasMaxLimit()) {
        hash = (37 * hash) + MAXLIMIT_FIELD_NUMBER;
        hash = (53 * hash) + getMaxLimit();
      }
      if (getValuesListCount() > 0) {
        hash = (37 * hash) + VALUESLIST_FIELD_NUMBER;
        hash = (53 * hash) + getValuesListList().hashCode();
      }
      if (hasSupportsMonitoring()) {
        hash = (37 * hash) + SUPPORTSMONITORING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSupportsMonitoring());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
     
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code variableCharacteristicsType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:variableCharacteristicsType)
        com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.internal_static_variableCharacteristicsType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.internal_static_variableCharacteristicsType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.class, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        units_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        minLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        valuesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        supportsMonitoring_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.internal_static_variableCharacteristicsType_descriptor;
      }

       
      public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDefaultInstance();
      }

       
      public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType build() {
        com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

       
      public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType buildPartial() {
        com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType result = new com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.units_ = units_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dataType_ = dataType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.minLimit_ = minLimit_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxLimit_ = maxLimit_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          valuesList_ = valuesList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.valuesList_ = valuesList_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.supportsMonitoring_ = supportsMonitoring_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType) {
          return mergeFrom((com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType other) {
        if (other == com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDefaultInstance()) return this;
        if (other.hasUnits()) {
          bitField0_ |= 0x00000001;
          units_ = other.units_;
          onChanged();
        }
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        if (other.hasMinLimit()) {
          setMinLimit(other.getMinLimit());
        }
        if (other.hasMaxLimit()) {
          setMaxLimit(other.getMaxLimit());
        }
        if (!other.valuesList_.isEmpty()) {
          if (valuesList_.isEmpty()) {
            valuesList_ = other.valuesList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureValuesListIsMutable();
            valuesList_.addAll(other.valuesList_);
          }
          onChanged();
        }
        if (other.hasSupportsMonitoring()) {
          setSupportsMonitoring(other.getSupportsMonitoring());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUnits()) {
          return false;
        }
        if (!hasDataType()) {
          return false;
        }
        if (!hasSupportsMonitoring()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object units_ = "";
      /**
       * <pre>
       *属�?��?�单�?
       * </pre>
       *
       * <code>required string units = 1;</code>
       */
      public boolean hasUnits() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *属�?��?�单�?
       * </pre>
       *
       * <code>required string units = 1;</code>
       */
      public java.lang.String getUnits() {
        java.lang.Object ref = units_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            units_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *属�?��?�单�?
       * </pre>
       *
       * <code>required string units = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUnitsBytes() {
        java.lang.Object ref = units_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          units_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *属�?��?�单�?
       * </pre>
       *
       * <code>required string units = 1;</code>
       */
      public Builder setUnits(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        units_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *属�?��?�单�?
       * </pre>
       *
       * <code>required string units = 1;</code>
       */
      public Builder clearUnits() {
        bitField0_ = (bitField0_ & ~0x00000001);
        units_ = getDefaultInstance().getUnits();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *属�?��?�单�?
       * </pre>
       *
       * <code>required string units = 1;</code>
       */
      public Builder setUnitsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        units_ = value;
        onChanged();
        return this;
      }

      private int dataType_ = 0;
      /**
       * <pre>
       *属�?�数据类�?
       * </pre>
       *
       * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *属�?�数据类�?
       * </pre>
       *
       * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType getDataType() {
        @SuppressWarnings("deprecation")
        com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType result = com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType.valueOf(dataType_);
        return result == null ? com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType.String : result;
      }
      /**
       * <pre>
       *属�?�数据类�?
       * </pre>
       *
       * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
       */
      public Builder setDataType(com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.DateEnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *属�?�数据类�?
       * </pre>
       *
       * <code>required .variableCharacteristicsType.DateEnumType dataType = 2;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataType_ = 0;
        onChanged();
        return this;
      }

      private int minLimit_ ;
      /**
       * <pre>
       *默认固定�?小�??
       * </pre>
       *
       * <code>optional int32 minLimit = 3;</code>
       */
      public boolean hasMinLimit() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *默认固定�?小�??
       * </pre>
       *
       * <code>optional int32 minLimit = 3;</code>
       */
      public int getMinLimit() {
        return minLimit_;
      }
      /**
       * <pre>
       *默认固定�?小�??
       * </pre>
       *
       * <code>optional int32 minLimit = 3;</code>
       */
      public Builder setMinLimit(int value) {
        bitField0_ |= 0x00000004;
        minLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *默认固定�?小�??
       * </pre>
       *
       * <code>optional int32 minLimit = 3;</code>
       */
      public Builder clearMinLimit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        minLimit_ = 0;
        onChanged();
        return this;
      }

      private int maxLimit_ ;
      /**
       * <pre>
       *默认固定�?大�??
       * </pre>
       *
       * <code>optional int32 maxLimit = 4;</code>
       */
      public boolean hasMaxLimit() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *默认固定�?大�??
       * </pre>
       *
       * <code>optional int32 maxLimit = 4;</code>
       */
      public int getMaxLimit() {
        return maxLimit_;
      }
      /**
       * <pre>
       *默认固定�?大�??
       * </pre>
       *
       * <code>optional int32 maxLimit = 4;</code>
       */
      public Builder setMaxLimit(int value) {
        bitField0_ |= 0x00000008;
        maxLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *默认固定�?大�??
       * </pre>
       *
       * <code>optional int32 maxLimit = 4;</code>
       */
      public Builder clearMaxLimit() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxLimit_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList valuesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          valuesList_ = new com.google.protobuf.LazyStringArrayList(valuesList_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesListList() {
        return valuesList_.getUnmodifiableView();
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public int getValuesListCount() {
        return valuesList_.size();
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public java.lang.String getValuesList(int index) {
        return valuesList_.get(index);
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValuesListBytes(int index) {
        return valuesList_.getByteString(index);
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public Builder setValuesList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesListIsMutable();
        valuesList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public Builder addValuesList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesListIsMutable();
        valuesList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public Builder addAllValuesList(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, valuesList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public Builder clearValuesList() {
        valuesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当类型是OptionList时�?�，指向允许值列表（字符串列�?)
       * </pre>
       *
       * <code>repeated string valuesList = 5;</code>
       */
      public Builder addValuesListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesListIsMutable();
        valuesList_.add(value);
        onChanged();
        return this;
      }

      private boolean supportsMonitoring_ ;
      /**
       * <pre>
       *该字段是否被监控，当改变时�?�会notifyEvent会上�?
       * </pre>
       *
       * <code>required bool supportsMonitoring = 6;</code>
       */
      public boolean hasSupportsMonitoring() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *该字段是否被监控，当改变时�?�会notifyEvent会上�?
       * </pre>
       *
       * <code>required bool supportsMonitoring = 6;</code>
       */
      public boolean getSupportsMonitoring() {
        return supportsMonitoring_;
      }
      /**
       * <pre>
       *该字段是否被监控，当改变时�?�会notifyEvent会上�?
       * </pre>
       *
       * <code>required bool supportsMonitoring = 6;</code>
       */
      public Builder setSupportsMonitoring(boolean value) {
        bitField0_ |= 0x00000020;
        supportsMonitoring_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *该字段是否被监控，当改变时�?�会notifyEvent会上�?
       * </pre>
       *
       * <code>required bool supportsMonitoring = 6;</code>
       */
      public Builder clearSupportsMonitoring() {
        bitField0_ = (bitField0_ & ~0x00000020);
        supportsMonitoring_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:variableCharacteristicsType)
    }

    // @@protoc_insertion_point(class_scope:variableCharacteristicsType)
    private static final com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType();
    }

    public static com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<variableCharacteristicsType>
        PARSER = new com.google.protobuf.AbstractParser<variableCharacteristicsType>() {
      public variableCharacteristicsType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new variableCharacteristicsType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<variableCharacteristicsType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<variableCharacteristicsType> getParserForType() {
      return PARSER;
    }

     
    public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_variableCharacteristicsType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_variableCharacteristicsType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!variableCharacteristicsType.proto\"\236\002\n\033" +
      "variableCharacteristicsType\022\r\n\005units\030\001 \002" +
      "(\t\022;\n\010dataType\030\002 \002(\0162).variableCharacter" +
      "isticsType.DateEnumType\022\020\n\010minLimit\030\003 \001(" +
      "\005\022\020\n\010maxLimit\030\004 \001(\005\022\022\n\nvaluesList\030\005 \003(\t\022" +
      "\032\n\022supportsMonitoring\030\006 \002(\010\"_\n\014DateEnumT" +
      "ype\022\n\n\006String\020\000\022\013\n\007Decimal\020\001\022\013\n\007Integer\020" +
      "\002\022\014\n\010DateTime\020\003\022\013\n\007Boolean\020\004\022\016\n\nOptionLi" +
      "st\020\005BD\n com.zhicheng.wukongcharge.models" +
      "B VariableCharacteristicsTypeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_variableCharacteristicsType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_variableCharacteristicsType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_variableCharacteristicsType_descriptor,
        new java.lang.String[] { "Units", "DataType", "MinLimit", "MaxLimit", "ValuesList", "SupportsMonitoring", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
