// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableType.proto

package com.zhicheng.wukongcharge.models;

public final class VariableTypeProto {
  private VariableTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface variableTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:variableType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *变量�?
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <pre>
     *变量�?
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *变量�?
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *变量实例(暂时未使�?)
     * </pre>
     *
     * <code>optional string instance = 2;</code>
     */
    boolean hasInstance();
    /**
     * <pre>
     *变量实例(暂时未使�?)
     * </pre>
     *
     * <code>optional string instance = 2;</code>
     */
    java.lang.String getInstance();
    /**
     * <pre>
     *变量实例(暂时未使�?)
     * </pre>
     *
     * <code>optional string instance = 2;</code>
     */
    com.google.protobuf.ByteString
        getInstanceBytes();

    /**
     * <pre>
     *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
     * </pre>
     *
     * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
     */
    boolean hasVariableCharacteristics();
    /**
     * <pre>
     *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
     * </pre>
     *
     * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
     */
    com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType getVariableCharacteristics();
    /**
     * <pre>
     *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
     * </pre>
     *
     * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
     */
    com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsTypeOrBuilder getVariableCharacteristicsOrBuilder();
  }
  /**
   * Protobuf type {@code variableType}
   */
  public  static final class variableType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:variableType)
      variableTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use variableType.newBuilder() to construct.
    private variableType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private variableType() {
      name_ = "";
      instance_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private variableType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              instance_ = bs;
              break;
            }
            case 26: {
              com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = variableCharacteristics_.toBuilder();
              }
              variableCharacteristics_ = input.readMessage(com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(variableCharacteristics_);
                variableCharacteristics_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhicheng.wukongcharge.models.VariableTypeProto.internal_static_variableType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhicheng.wukongcharge.models.VariableTypeProto.internal_static_variableType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.class, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *变量�?
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *变量�?
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *变量�?
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTANCE_FIELD_NUMBER = 2;
    private volatile java.lang.Object instance_;
    /**
     * <pre>
     *变量实例(暂时未使�?)
     * </pre>
     *
     * <code>optional string instance = 2;</code>
     */
    public boolean hasInstance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *变量实例(暂时未使�?)
     * </pre>
     *
     * <code>optional string instance = 2;</code>
     */
    public java.lang.String getInstance() {
      java.lang.Object ref = instance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instance_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *变量实例(暂时未使�?)
     * </pre>
     *
     * <code>optional string instance = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceBytes() {
      java.lang.Object ref = instance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VARIABLECHARACTERISTICS_FIELD_NUMBER = 3;
    private com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType variableCharacteristics_;
    /**
     * <pre>
     *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
     * </pre>
     *
     * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
     */
    public boolean hasVariableCharacteristics() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
     * </pre>
     *
     * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
     */
    public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType getVariableCharacteristics() {
      return variableCharacteristics_ == null ? com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDefaultInstance() : variableCharacteristics_;
    }
    /**
     * <pre>
     *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
     * </pre>
     *
     * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
     */
    public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsTypeOrBuilder getVariableCharacteristicsOrBuilder() {
      return variableCharacteristics_ == null ? com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDefaultInstance() : variableCharacteristics_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasVariableCharacteristics()) {
        if (!getVariableCharacteristics().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, instance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getVariableCharacteristics());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, instance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getVariableCharacteristics());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhicheng.wukongcharge.models.VariableTypeProto.variableType)) {
        return super.equals(obj);
      }
      com.zhicheng.wukongcharge.models.VariableTypeProto.variableType other = (com.zhicheng.wukongcharge.models.VariableTypeProto.variableType) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasInstance() == other.hasInstance());
      if (hasInstance()) {
        result = result && getInstance()
            .equals(other.getInstance());
      }
      result = result && (hasVariableCharacteristics() == other.hasVariableCharacteristics());
      if (hasVariableCharacteristics()) {
        result = result && getVariableCharacteristics()
            .equals(other.getVariableCharacteristics());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasInstance()) {
        hash = (37 * hash) + INSTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getInstance().hashCode();
      }
      if (hasVariableCharacteristics()) {
        hash = (37 * hash) + VARIABLECHARACTERISTICS_FIELD_NUMBER;
        hash = (53 * hash) + getVariableCharacteristics().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
     
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code variableType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:variableType)
        com.zhicheng.wukongcharge.models.VariableTypeProto.variableTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhicheng.wukongcharge.models.VariableTypeProto.internal_static_variableType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhicheng.wukongcharge.models.VariableTypeProto.internal_static_variableType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.class, com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.Builder.class);
      }

      // Construct using com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVariableCharacteristicsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        instance_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (variableCharacteristicsBuilder_ == null) {
          variableCharacteristics_ = null;
        } else {
          variableCharacteristicsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhicheng.wukongcharge.models.VariableTypeProto.internal_static_variableType_descriptor;
      }

       
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getDefaultInstanceForType() {
        return com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance();
      }

       
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType build() {
        com.zhicheng.wukongcharge.models.VariableTypeProto.variableType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

       
      public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType buildPartial() {
        com.zhicheng.wukongcharge.models.VariableTypeProto.variableType result = new com.zhicheng.wukongcharge.models.VariableTypeProto.variableType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.instance_ = instance_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (variableCharacteristicsBuilder_ == null) {
          result.variableCharacteristics_ = variableCharacteristics_;
        } else {
          result.variableCharacteristics_ = variableCharacteristicsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhicheng.wukongcharge.models.VariableTypeProto.variableType) {
          return mergeFrom((com.zhicheng.wukongcharge.models.VariableTypeProto.variableType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhicheng.wukongcharge.models.VariableTypeProto.variableType other) {
        if (other == com.zhicheng.wukongcharge.models.VariableTypeProto.variableType.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasInstance()) {
          bitField0_ |= 0x00000002;
          instance_ = other.instance_;
          onChanged();
        }
        if (other.hasVariableCharacteristics()) {
          mergeVariableCharacteristics(other.getVariableCharacteristics());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (hasVariableCharacteristics()) {
          if (!getVariableCharacteristics().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhicheng.wukongcharge.models.VariableTypeProto.variableType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhicheng.wukongcharge.models.VariableTypeProto.variableType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *变量�?
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *变量�?
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *变量�?
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *变量�?
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *变量�?
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *变量�?
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object instance_ = "";
      /**
       * <pre>
       *变量实例(暂时未使�?)
       * </pre>
       *
       * <code>optional string instance = 2;</code>
       */
      public boolean hasInstance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *变量实例(暂时未使�?)
       * </pre>
       *
       * <code>optional string instance = 2;</code>
       */
      public java.lang.String getInstance() {
        java.lang.Object ref = instance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            instance_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *变量实例(暂时未使�?)
       * </pre>
       *
       * <code>optional string instance = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInstanceBytes() {
        java.lang.Object ref = instance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *变量实例(暂时未使�?)
       * </pre>
       *
       * <code>optional string instance = 2;</code>
       */
      public Builder setInstance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        instance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *变量实例(暂时未使�?)
       * </pre>
       *
       * <code>optional string instance = 2;</code>
       */
      public Builder clearInstance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        instance_ = getDefaultInstance().getInstance();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *变量实例(暂时未使�?)
       * </pre>
       *
       * <code>optional string instance = 2;</code>
       */
      public Builder setInstanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        instance_ = value;
        onChanged();
        return this;
      }

      private com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType variableCharacteristics_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsTypeOrBuilder> variableCharacteristicsBuilder_;
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public boolean hasVariableCharacteristics() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType getVariableCharacteristics() {
        if (variableCharacteristicsBuilder_ == null) {
          return variableCharacteristics_ == null ? com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDefaultInstance() : variableCharacteristics_;
        } else {
          return variableCharacteristicsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public Builder setVariableCharacteristics(com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType value) {
        if (variableCharacteristicsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          variableCharacteristics_ = value;
          onChanged();
        } else {
          variableCharacteristicsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public Builder setVariableCharacteristics(
          com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder builderForValue) {
        if (variableCharacteristicsBuilder_ == null) {
          variableCharacteristics_ = builderForValue.build();
          onChanged();
        } else {
          variableCharacteristicsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public Builder mergeVariableCharacteristics(com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType value) {
        if (variableCharacteristicsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              variableCharacteristics_ != null &&
              variableCharacteristics_ != com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDefaultInstance()) {
            variableCharacteristics_ =
              com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.newBuilder(variableCharacteristics_).mergeFrom(value).buildPartial();
          } else {
            variableCharacteristics_ = value;
          }
          onChanged();
        } else {
          variableCharacteristicsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public Builder clearVariableCharacteristics() {
        if (variableCharacteristicsBuilder_ == null) {
          variableCharacteristics_ = null;
          onChanged();
        } else {
          variableCharacteristicsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder getVariableCharacteristicsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getVariableCharacteristicsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      public com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsTypeOrBuilder getVariableCharacteristicsOrBuilder() {
        if (variableCharacteristicsBuilder_ != null) {
          return variableCharacteristicsBuilder_.getMessageOrBuilder();
        } else {
          return variableCharacteristics_ == null ?
              com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.getDefaultInstance() : variableCharacteristics_;
        }
      }
      /**
       * <pre>
       *属�?�，如�?�单位，�?大�?�，�?小�?�，允许值列�?,是否监控
       * </pre>
       *
       * <code>optional .variableCharacteristicsType variableCharacteristics = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsTypeOrBuilder> 
          getVariableCharacteristicsFieldBuilder() {
        if (variableCharacteristicsBuilder_ == null) {
          variableCharacteristicsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsType.Builder, com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.variableCharacteristicsTypeOrBuilder>(
                  getVariableCharacteristics(),
                  getParentForChildren(),
                  isClean());
          variableCharacteristics_ = null;
        }
        return variableCharacteristicsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:variableType)
    }

    // @@protoc_insertion_point(class_scope:variableType)
    private static final com.zhicheng.wukongcharge.models.VariableTypeProto.variableType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhicheng.wukongcharge.models.VariableTypeProto.variableType();
    }

    public static com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<variableType>
        PARSER = new com.google.protobuf.AbstractParser<variableType>() {
      public variableType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new variableType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<variableType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<variableType> getParserForType() {
      return PARSER;
    }

     
    public com.zhicheng.wukongcharge.models.VariableTypeProto.variableType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_variableType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_variableType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022variableType.proto\032!variableCharacteri" +
      "sticsType.proto\"m\n\014variableType\022\014\n\004name\030" +
      "\001 \002(\t\022\020\n\010instance\030\002 \001(\t\022=\n\027variableChara" +
      "cteristics\030\003 \001(\0132\034.variableCharacteristi" +
      "csTypeB5\n com.charge.protocol.tomda.mode" +
      "lsB\021VariableTypeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.getDescriptor(),
        }, assigner);
    internal_static_variableType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_variableType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_variableType_descriptor,
        new java.lang.String[] { "Name", "Instance", "VariableCharacteristics", });
    com.zhicheng.wukongcharge.models.VariableCharacteristicsTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
